config:
  app:
    name: "ChatRoom"
    version: "1.0.0"
    description: "A simple chat room"

  server:
    host: "0.0.0.0"
    port: 8888
    max_connections: 100
    buffer_size: 1024

  security:
    password_salt: "ChatRoom_Salt_Value_For_Password_Hashing_2025"
  
  users:
    valid_users: {}